[2022-03-27 12:19:09,364] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: python_operator.print manual__2022-03-27T17:18:59.435387+00:00 [queued]>
[2022-03-27 12:19:09,373] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: python_operator.print manual__2022-03-27T17:18:59.435387+00:00 [queued]>
[2022-03-27 12:19:09,373] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-27 12:19:09,373] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-27 12:19:09,373] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-27 12:19:09,548] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): print> on 2022-03-27 17:18:59.435387+00:00
[2022-03-27 12:19:09,551] {standard_task_runner.py:52} INFO - Started process 11833 to run task
[2022-03-27 12:19:09,554] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'python_operator', 'print', 'manual__2022-03-27T17:18:59.435387+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/etl_python_operator.py', '--cfg-path', '/tmp/tmp3vraizlt', '--error-file', '/tmp/tmp8zs1grxc']
[2022-03-27 12:19:09,555] {standard_task_runner.py:77} INFO - Job 145: Subtask print
[2022-03-27 12:19:09,781] {logging_mixin.py:109} INFO - Running <TaskInstance: python_operator.print manual__2022-03-27T17:18:59.435387+00:00 [running]> on host LAPTOP-5HJG55H7.localdomain
[2022-03-27 12:19:10,104] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=python_operator
AIRFLOW_CTX_TASK_ID=print
AIRFLOW_CTX_EXECUTION_DATE=2022-03-27T17:18:59.435387+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-27T17:18:59.435387+00:00
[2022-03-27 12:19:10,112] {base.py:70} INFO - Using connection to: id: airflow-universities. Host: training-main.cghe7e6sfljt.us-east-1.rds.amazonaws.com, Port: 5432, Schema: training, Login: alkymer, Password: ***, extra: {}
[2022-03-27 12:19:10,705] {dbapi.py:225} INFO - Running statement: -- Task PT172-19
-- Obtener los datos de las pesonas anotadas en entre las fechas 01/9/2020 al 01/02/2021 para
-- las siguientes facultades:
-- Universidad De Buenos Aires

select
        universidades, carreras, fechas_de_inscripcion, nombres, sexo, fechas_nacimiento, codigos_postales
from
        uba_kenedy uk
where
        TO_DATE(fechas_de_inscripcion, 'YY-MON-DD') between '2020-09-01' and '2021-02-01'
        and universidades = 'universidad-de-buenos-aires'
limit 3
;
, parameters: None
[2022-03-27 12:19:10,859] {dbapi.py:233} INFO - Rows affected: 3
[2022-03-27 12:19:10,945] {logging_mixin.py:109} INFO - ['_BaseOperator__instantiated', '_BaseOperator__serialized_fields', '__abstractmethods__', '__annotations__', '__class__', '__deepcopy__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lshift__', '__lt__', '__module__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__rlshift__', '__rrshift__', '__rshift__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_base_operator_shallow_copy_attrs', '_comps', '_dag', '_do_render_template_fields', '_downstream_task_ids', '_inlets', '_lock_for_execution', '_log', '_outlets', '_post_execute_hook', '_pre_execute_hook', '_render_nested_template_fields', '_set_context', '_set_relatives', '_upstream_task_ids', 'add_inlets', 'add_only_new', 'add_outlets', 'autocommit', 'clear', 'dag', 'dag_id', 'database', 'defer', 'depends_on_past', 'deps', 'do_xcom_push', 'doc', 'doc_json', 'doc_md', 'doc_rst', 'doc_yaml', 'downstream_list', 'downstream_task_ids', 'dry_run', 'email', 'email_on_failure', 'email_on_retry', 'end_date', 'execute', 'execution_timeout', 'executor_config', 'extra_links', 'get_direct_relative_ids', 'get_direct_relatives', 'get_extra_links', 'get_flat_relative_ids', 'get_flat_relatives', 'get_inlet_defs', 'get_outlet_defs', 'get_serialized_fields', 'get_task_instances', 'get_template_env', 'global_operator_extra_link_dict', 'has_dag', 'hook', 'inherits_from_dummy_operator', 'inlets', 'is_smart_sensor_compatible', 'label', 'leaves', 'log', 'max_active_tis_per_dag', 'max_retry_delay', 'on_execute_callback', 'on_failure_callback', 'on_kill', 'on_retry_callback', 'on_success_callback', 'operator_extra_link_dict', 'operator_extra_links', 'outlets', 'output', 'owner', 'parameters', 'params', 'pool', 'pool_slots', 'post_execute', 'postgres_conn_id', 'pre_execute', 'prepare_for_execution', 'prepare_template', 'priority_weight', 'priority_weight_total', 'queue', 'render_template', 'render_template_fields', 'resolve_template_files', 'resources', 'retries', 'retry_delay', 'retry_exponential_backoff', 'roots', 'run', 'run_as_user', 'set_downstream', 'set_upstream', 'set_xcomargs_dependencies', 'shallow_copy_attrs', 'sla', 'sql', 'start_date', 'subdag', 'supports_lineage', 'task_id', 'task_type', 'template_ext', 'template_fields', 'template_fields_renderers', 'trigger_rule', 'ui_color', 'ui_fgcolor', 'update_relative', 'upstream_list', 'upstream_task_ids', 'wait_for_downstream', 'weight_rule', 'xcom_pull', 'xcom_push']
[2022-03-27 12:19:10,945] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/lowenhard/airflow/dags/etl_python_operator.py", line 57, in test1
    return sql_query.sql()
TypeError: 'str' object is not callable
[2022-03-27 12:19:11,083] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=python_operator, task_id=print, execution_date=20220327T171859, start_date=20220327T171909, end_date=20220327T171911
[2022-03-27 12:19:11,289] {standard_task_runner.py:89} ERROR - Failed to execute job 145 for task print
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/lowenhard/airflow/dags/etl_python_operator.py", line 57, in test1
    return sql_query.sql()
TypeError: 'str' object is not callable
[2022-03-27 12:19:11,296] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-27 12:19:11,517] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
