[2022-04-03 03:15:10,845] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: hello_dag.print_info manual__2022-04-03T08:13:57.791110+00:00 [queued]>
[2022-04-03 03:15:10,851] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: hello_dag.print_info manual__2022-04-03T08:13:57.791110+00:00 [queued]>
[2022-04-03 03:15:10,852] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-03 03:15:10,852] {taskinstance.py:1244} INFO - Starting attempt 2 of 2
[2022-04-03 03:15:10,852] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-03 03:15:11,052] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): print_info> on 2022-04-03 08:13:57.791110+00:00
[2022-04-03 03:15:11,054] {standard_task_runner.py:52} INFO - Started process 942 to run task
[2022-04-03 03:15:11,059] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'hello_dag', 'print_info', 'manual__2022-04-03T08:13:57.791110+00:00', '--job-id', '238', '--raw', '--subdir', 'DAGS_FOLDER/dag_example.py', '--cfg-path', '/tmp/tmpqk1eymxb', '--error-file', '/tmp/tmpm76o0k47']
[2022-04-03 03:15:11,060] {standard_task_runner.py:77} INFO - Job 238: Subtask print_info
[2022-04-03 03:15:11,556] {logging_mixin.py:109} INFO - Running <TaskInstance: hello_dag.print_info manual__2022-04-03T08:13:57.791110+00:00 [running]> on host LAPTOP-5HJG55H7.localdomain
[2022-04-03 03:15:12,325] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1423, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2011, in render_templates
    self.task.render_template_fields(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1061, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1074, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1113, in render_template
    return render_template_to_string(template, context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/helpers.py", line 268, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/helpers.py", line 263, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'AIRFLOW_CTX_DAG_OWNER' is undefined
[2022-04-03 03:15:12,332] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=hello_dag, task_id=print_info, execution_date=20220403T081357, start_date=20220403T081510, end_date=20220403T081512
[2022-04-03 03:15:12,635] {standard_task_runner.py:89} ERROR - Failed to execute job 238 for task print_info
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1423, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2011, in render_templates
    self.task.render_template_fields(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1061, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1074, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1113, in render_template
    return render_template_to_string(template, context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/helpers.py", line 268, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/helpers.py", line 263, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'AIRFLOW_CTX_DAG_OWNER' is undefined
[2022-04-03 03:15:12,679] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-03 03:15:12,847] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
