[2022-04-03 22:36:29,250] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: python_operator_univ_flores.dataframe_task manual__2022-04-04T03:36:04.441214+00:00 [queued]>
[2022-04-03 22:36:29,264] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: python_operator_univ_flores.dataframe_task manual__2022-04-04T03:36:04.441214+00:00 [queued]>
[2022-04-03 22:36:29,264] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-03 22:36:29,264] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-04-03 22:36:29,264] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-03 22:36:29,479] {taskinstance.py:1264} INFO - Executing <Task(_PythonDecoratedOperator): dataframe_task> on 2022-04-04 03:36:04.441214+00:00
[2022-04-03 22:36:29,483] {standard_task_runner.py:52} INFO - Started process 3382 to run task
[2022-04-03 22:36:29,489] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'python_operator_univ_flores', 'dataframe_task', 'manual__2022-04-04T03:36:04.441214+00:00', '--job-id', '335', '--raw', '--subdir', 'DAGS_FOLDER/ET_Univ_De_Flores_dag.py', '--cfg-path', '/tmp/tmp5_6z0du3', '--error-file', '/tmp/tmpin0rfioi']
[2022-04-03 22:36:29,490] {standard_task_runner.py:77} INFO - Job 335: Subtask dataframe_task
[2022-04-03 22:36:29,914] {logging_mixin.py:109} INFO - Running <TaskInstance: python_operator_univ_flores.dataframe_task manual__2022-04-04T03:36:04.441214+00:00 [running]> on host LAPTOP-5HJG55H7.localdomain
[2022-04-03 22:36:30,878] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=python_operator_univ_flores
AIRFLOW_CTX_TASK_ID=dataframe_task
AIRFLOW_CTX_EXECUTION_DATE=2022-04-04T03:36:04.441214+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-04T03:36:04.441214+00:00
[2022-04-03 22:36:30,959] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/lowenhard/airflow/dags/ET_Univ_De_Flores_dag.py", line 92, in dataframe_task
    log.info(f'df created {json.dumps(d.columns)}')
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Index is not JSON serializable
[2022-04-03 22:36:30,967] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=python_operator_univ_flores, task_id=dataframe_task, execution_date=20220404T033604, start_date=20220404T033629, end_date=20220404T033630
[2022-04-03 22:36:31,156] {standard_task_runner.py:89} ERROR - Failed to execute job 335 for task dataframe_task
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/lowenhard/airflow/dags/ET_Univ_De_Flores_dag.py", line 92, in dataframe_task
    log.info(f'df created {json.dumps(d.columns)}')
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Index is not JSON serializable
[2022-04-03 22:36:31,190] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-03 22:36:31,421] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
