[2022-04-03 20:54:24,808] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: pandas_python_operator.get_dataframe manual__2022-04-04T01:54:17.740914+00:00 [queued]>
[2022-04-03 20:54:24,818] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: pandas_python_operator.get_dataframe manual__2022-04-04T01:54:17.740914+00:00 [queued]>
[2022-04-03 20:54:24,819] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-03 20:54:24,819] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-04-03 20:54:24,819] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-03 20:54:25,038] {taskinstance.py:1264} INFO - Executing <Task(_PythonDecoratedOperator): get_dataframe> on 2022-04-04 01:54:17.740914+00:00
[2022-04-03 20:54:25,042] {standard_task_runner.py:52} INFO - Started process 316 to run task
[2022-04-03 20:54:25,047] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'pandas_python_operator', 'get_dataframe', 'manual__2022-04-04T01:54:17.740914+00:00', '--job-id', '310', '--raw', '--subdir', 'DAGS_FOLDER/ET_Univ_Villa_Maria_dag.py', '--cfg-path', '/tmp/tmpb2lzfuro', '--error-file', '/tmp/tmpp3ftztzr']
[2022-04-03 20:54:25,048] {standard_task_runner.py:77} INFO - Job 310: Subtask get_dataframe
[2022-04-03 20:54:25,334] {logging_mixin.py:109} INFO - Running <TaskInstance: pandas_python_operator.get_dataframe manual__2022-04-04T01:54:17.740914+00:00 [running]> on host LAPTOP-5HJG55H7.localdomain
[2022-04-03 20:54:25,660] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=pandas_python_operator
AIRFLOW_CTX_TASK_ID=get_dataframe
AIRFLOW_CTX_EXECUTION_DATE=2022-04-04T01:54:17.740914+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-04T01:54:17.740914+00:00
[2022-04-03 20:54:25,677] {base.py:70} INFO - Using connection to: id: airflow-universities. Host: training-main.cghe7e6sfljt.us-east-1.rds.amazonaws.com, Port: 5432, Schema: training, Login: alkymer, Password: ***, extra: {}
[2022-04-03 20:54:27,843] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/lowenhard/airflow/dags/ET_Univ_Villa_Maria_dag.py", line 85, in get_villa_maria_df
    dataframe = process_dataframe(dataframe)
TypeError: process_dataframe() takes 0 positional arguments but 1 was given
[2022-04-03 20:54:28,087] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=pandas_python_operator, task_id=get_dataframe, execution_date=20220404T015417, start_date=20220404T015424, end_date=20220404T015428
[2022-04-03 20:54:28,607] {standard_task_runner.py:89} ERROR - Failed to execute job 310 for task get_dataframe
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/lowenhard/airflow/dags/ET_Univ_Villa_Maria_dag.py", line 85, in get_villa_maria_df
    dataframe = process_dataframe(dataframe)
TypeError: process_dataframe() takes 0 positional arguments but 1 was given
[2022-04-03 20:54:28,642] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-03 20:54:29,074] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
