[2022-03-27 11:39:48,477] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: python_operator.print manual__2022-03-27T16:39:38.974456+00:00 [queued]>
[2022-03-27 11:39:48,485] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: python_operator.print manual__2022-03-27T16:39:38.974456+00:00 [queued]>
[2022-03-27 11:39:48,485] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-27 11:39:48,485] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-27 11:39:48,485] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-27 11:39:48,796] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): print> on 2022-03-27 16:39:38.974456+00:00
[2022-03-27 11:39:48,815] {standard_task_runner.py:52} INFO - Started process 10089 to run task
[2022-03-27 11:39:48,819] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'python_operator', 'print', 'manual__2022-03-27T16:39:38.974456+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/etl_python_operator.py', '--cfg-path', '/tmp/tmpm935bmp7', '--error-file', '/tmp/tmpdm6smv7u']
[2022-03-27 11:39:48,819] {standard_task_runner.py:77} INFO - Job 136: Subtask print
[2022-03-27 11:39:49,165] {logging_mixin.py:109} INFO - Running <TaskInstance: python_operator.print manual__2022-03-27T16:39:38.974456+00:00 [running]> on host LAPTOP-5HJG55H7.localdomain
[2022-03-27 11:39:52,865] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=python_operator
AIRFLOW_CTX_TASK_ID=print
AIRFLOW_CTX_EXECUTION_DATE=2022-03-27T16:39:38.974456+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-27T16:39:38.974456+00:00
[2022-03-27 11:39:52,867] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/lowenhard/airflow/dags/etl_python_operator.py", line 50, in test1
    data = sql_query.execute()
TypeError: execute() missing 1 required positional argument: 'context'
[2022-03-27 11:39:52,884] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=python_operator, task_id=print, execution_date=20220327T163938, start_date=20220327T163948, end_date=20220327T163952
[2022-03-27 11:39:53,366] {standard_task_runner.py:89} ERROR - Failed to execute job 136 for task print
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/lowenhard/airflow/dags/etl_python_operator.py", line 50, in test1
    data = sql_query.execute()
TypeError: execute() missing 1 required positional argument: 'context'
[2022-03-27 11:39:53,376] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-27 11:39:55,858] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
